sudo: required
services: 
    - docker

before_install: 
    - docker build -t aalmomany/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aalmomany/docker-react npm run test -- --coverage