sudo: required
services: 
    - docker

before_install: 
    - docker build -t aalmomany/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aalmomany/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker" #app name
    env: "Docker-env" #Environmet name 
    bucket_name: "elasticbeanstalk-us-east-2-530364731450"
    bucket_path: "docker" #Path to be created if not there 
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY